anaden_tool/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

app/urls.py
from django.urls import path
from . import views
from .views import IndexView,StorysView,SubTaskConditionChangeView,GaitensView,GaidensView,KaikousView,DansyosView,KyosousView

app_name = 'app'

urlpatterns = [
    path('',IndexView.as_view(),name='index'), #トップ画面処理(今のところストーリーにリダイレクトするだけ)
    path('storys/',StorysView.as_view(),name='storys'), #ストーリー画面
    path('subtask_update/',SubTaskConditionChangeView.as_view(),name="condition_change"), #Ajaxタスク状態変化処理
    path('gaitens/',GaitensView.as_view(),name='gaitens'), #外典クエスト画面
    path('gaidens/',GaidensView.as_view(),name='gaidens'), #外伝クエスト画面
    path('kaikous/',KaikousView.as_view(),name='kaikous'), #邂逅クエスト画面
    path('dansyos/',DansyosView.as_view(),name='dansyos'), #断章クエスト画面
    path('kyosous/',KyosousView.as_view(),name='kyosous'), #協奏クエスト画面
]

app/models.py
from django.db import models



#メインタスク「メインストーリー前編」などのタイトルが表示される
class MainTask(models.Model):
    title = models.CharField('タイトル',max_length=64)
    TYPES = (
        (1,'メインストーリー'),
        (2,'外典'),
        (3,'外伝'),
        (4,'邂逅'),
        (5,'断章'),
        (6,'協奏'),
        (7,'オリジナルタスク'),
        (8,'その他'),
    )
    types = models.IntegerField('タイプ',choices=TYPES)
    task_seq = models.IntegerField('順序',null=True,blank=True)

    def __str__(self):
        return self.title


#サブタスク「第64話」みたいなメインに対する細かいタスクが入る
class SubTask(models.Model):
    main_task = models.ForeignKey(MainTask,on_delete=models.CASCADE)
    title = models.CharField('タイトル',max_length=128)
    content = models.TextField('詳細')
    CONDITIONS = (
        (1,'新規'),
        (2,'挑戦中'),
        (3,'完了'),
    )
    condition = models.IntegerField('状態',choices=CONDITIONS,default=1)
    task_seq = models.IntegerField('順序',null=True,blank=True)
    created_at = models.DateTimeField('作成日',auto_now=True)
    updated_at = models.DateTimeField('更新日',auto_now=True)

    # 状態変化を設定する関数(渡すのは状態の文字列にする)
    def setConditionChange(self,condition_str):
        if condition_str == "1":
            self.condition = 3
        elif condition_str == "3":
            self.condition = 1
        self.save()
        pass

    def __str__(self):
        return self.title

        
    

app/views.py
from django.shortcuts import render,redirect
from django.views import generic,View
from .models import MainTask,SubTask
from django.http.response import HttpResponse
import json

# イベント文字列に対するタイプ値を返す辞書
eventNumDict = {
    "story":1,
    "gaiten":2,
    "gaiden":3,
    "kaikou":4,
    "dansyo":5,
    "kyosou":6
}

# タイプの項目ごとの達成率を返す関数 return->項目ごとの達成率をセットした配列 ※storyのみ全体の達成率をそのまま返す
def get_main_achievement_rate(eventStr):
    # イベント番号に対するフィルターを掛け絞り込み
    main = MainTask.objects.filter(types=eventNumDict[eventStr])
    task_count = 0
    fin_task_count = 0
    if eventStr == "story":
        for task in main:
            task_count += task.subtask_set.all().count() # 全タスク数の取得
            fin_task_count += task.subtask_set.filter(condition=3).count() # 完了済みタスクの取得
        if task_count != 0:
            achievement_rate = round(( fin_task_count / task_count ) * 100,1) # 達成率の計算
            return achievement_rate
    else:
        achievementArray = [] #このリストに項目ごとの達成率を入れていく
        for task in main:
            task_count = task.subtask_set.all().count() # 全タスク数の取得
            fin_task_count = task.subtask_set.filter(condition=3).count() # 完了済みタスクの取得
            if task_count != 0:
                achievement_rate = round(( fin_task_count / task_count ) * 100,1) # 達成率の計算
            else:
                achievement_rate = 0
            achievementArray.append(achievement_rate) # 達成率を配列に退避
        return achievementArray
    



# タスクの状態を変更して完了メッセージを返す(Ajaxでアクセスされる想定)
class SubTaskConditionChangeView(View):
    def get(self,request,*args,**kwargs):
        task_id = request.GET.get('task_id') #subtaskのidの取得(採番数が増えるのでいずれ別の方法を検討すべき)
        condition = request.GET.get('condition') #現在のsubtaskの状態の取得
        req_type = request.GET.get('req_type') #リクエストタイプ(get_main_achievement_rateに繋げる)
        main_seq = request.GET.get('main_seq') #MainTaskのtypes(順序)、ない場合でもnoneを返す
        SubTask.objects.get(pk=task_id).setConditionChange(condition)
        if req_type == "story":
            achievement_rate = get_main_achievement_rate(req_type) #達成率の取得
        else:
            achievementArray = get_main_achievement_rate(req_type) #達成率リストを取得しカンマ区切りで連結
            achievement_rate = achievementArray[int(main_seq) - 1] #渡されたメインタスクの順序に合わせた達成率を取得

        data = {
            'success':'success',
            'achievement_rate':achievement_rate,
            'req_type':req_type,
            'main_seq':main_seq
        }
        
        # 辞書からjson形式にシリアライズ
        data_json = json.dumps(data)
        return HttpResponse(data_json,content_type='application/json')


# トップ画面はないのでストーリー一覧に飛ばす
class IndexView(generic.RedirectView):
    url = '/storys/'


# ストーリー画面のView
class StorysView(generic.ListView):
    template_name = "app/storys.html"
    model = MainTask
    context_object_name = "storys"

    # メインストーリーの情報だけ取得
    def get_queryset(self):
        # メインストーリーのデータだけ取得
        return MainTask.objects.filter(types=1)

    # ストーリー全体での達成率もセットする
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['achievement_rate'] = get_main_achievement_rate("story")
        return context


# 外典クエスト画面のView
class GaitensView(generic.ListView):
    template_name = "app/gaiten.html"
    model = MainTask
    context_object_name = "gaitens"

    # 外典クエストの情報だけ取得
    def get_queryset(self):
        #外典クエストのデータだけ取得
        return MainTask.objects.filter(types=2)

    # 外典の達成率もそれぞれ取得しセット(外典ごとに取得)
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['achievement_rates'] = get_main_achievement_rate("gaiten")
        return context


# 外伝クエスト画面のView
class GaidensView(generic.ListView):
    template_name = "app/event_view.html"
    model = MainTask
    context_object_name = "maintasks"

    # 外伝クエストの情報だけ取得
    def get_queryset(self):
        #外伝クエストのデータだけ取得
        return MainTask.objects.filter(types=3)

    # 外伝の達成率もそれぞれ取得しセット(contextオブジェクトにキーと値を入れておくとtemplateに持っていける)
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['achievement_rates'] = get_main_achievement_rate("gaiden")
        context['reqtype'] = "gaiden"
        return context


# 邂逅クエスト画面のView
class KaikousView(generic.ListView):
    template_name = "app/event_view.html"
    model = MainTask
    context_object_name = "maintasks"

    # 邂逅クエストの情報だけ取得
    def get_queryset(self):
        # 外伝クエストのデータだけ取得
        return MainTask.objects.filter(types=4)

    # 邂逅の達成率もそれぞれ取得しセット
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['achievement_rates'] = get_main_achievement_rate("kaikou")
        context['reqtype'] = "kaikou"
        return context


#断章クエスト画面のView
class DansyosView(generic.ListView):
    template_name = "app/event_view.html"
    model = MainTask
    context_object_name = "maintasks"

     # 邂逅クエストの情報だけ取得
    def get_queryset(self):
        # 外伝クエストのデータだけ取得
        return MainTask.objects.filter(types=5)

    # 邂逅の達成率もそれぞれ取得しセット
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['achievement_rates'] = get_main_achievement_rate("dansyo")
        context['reqtype'] = "dansyo"
        return context


#協奏クエスト画面のView
class KyosousView(generic.ListView):
    template_name = "app/event_view.html"
    model = MainTask
    context_object_name = "maintasks"

     # 協奏クエストの情報だけ取得
    def get_queryset(self):
        # 外伝クエストのデータだけ取得
        return MainTask.objects.filter(types=6)

    # 協奏の達成率もそれぞれ取得しセット
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['achievement_rates'] = get_main_achievement_rate("kyosou")
        context['reqtype'] = "kyosou"
        return context

templates/app/event_view.html
{% extends  "base.html" %}

{% block page_title %}外伝クエスト{% endblock %}

{% block content %}

<!-- イベントクエストタスクカードの設置-->
{% for maintask in maintasks %}
{% with forloop.counter as outer_counter %}
<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ maintask.title }}</h5>

        <!-- イベントクエスト達成率カードの設置-->
        {% for achievement_rate in achievement_rates %}
        {% with forloop.counter as inner_counter %}
        {% if outer_counter == inner_counter %}
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">あなたの{{ maintask.title }}の達成率は</h5>
                <div class="progress">
                    <div id="story-achieve-rate-bar-{{ maintask.task_seq }}" class="progress-bar progress-bar-striped progress-bar-animated" 
                    role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width:{{ achievement_rate }}%;text-align:center;"></div>
                </div>
                <div class="progress-values" style="text-align:center;">
                    <h3 id="story-achieve-rate-{{ maintask.task_seq }}">{{ achievement_rate }}%です</h3>
                </div>
            </div>
        </div>
        {% endif %}
        {% endwith %}
        {% endfor %}

<div style="height:2vh;"></div>

        {% load sort_tasks %}

        <!-- 新規タスクのみの一覧を出す -->
        <div class="new-tasks">
            {% for task in maintask.subtask_set.all|sort_task:'task_seq' %}
            {% if task.condition == 1 %}
            <div data-num="{{ task.task_seq }}">
                <div class="card task-contents" style="padding:0.3rem;">
                    <div class="row">
                        <div class="col-md-1" style="padding:0 0 0 30px;">
                            <div class="success_btn" data-taskid="{{ task.id }}" data-condition="{{ task.condition }}" data-reqtype="{{ reqtype }}" data-mainseq="{{ maintask.task_seq }}"></div>
                        </div>
                        <div class="col-md-11">
                            <p>{{ task.title }}</p>
                        </div>
                    </div>
                </div>
                <div class="card-space" style="height:0.3vh;"></div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        
        <div style="text-align:right;">
            <a class="fintask-btn" style="cursor:pointer;">完了済タスクを見る</a>
        </div>

        <!-- 完了タスクのみを出す(最初はここ非表示の予定) -->
        <div class="fin-tasks">
            {% for task in maintask.subtask_set.all|sort_task:'task_seq' %}
            {% if task.condition == 3 %}
            <div data-num="{{ task.task_seq }}">
                <div class="card task-contents" style="padding:0.3rem;">
                    <div class="row">
                        <div class="col-md-1" style="padding:0 0 0 30px;">
                            <div class="success_btn clicked" data-taskid="{{ task.id }}" data-condition="{{ task.condition }}" data-reqtype="{{ reqtype }}" data-mainseq="{{ maintask.task_seq }}"></div>
                        </div>
                        <div class="col-md-11">
                            <p>{{ task.title }}</p>
                        </div>
                    </div>
                </div>
                <div class="card-space" style="height:0.3vh;"></div>
            </div>
            {% endif %}
            {% endfor %}
        </div>


    </div>
</div>
<div style="height:1.5vh;"></div>
{% endwith %}
{% endfor %}

{% endblock %}

templates/app/gaiden.html
{% extends  "base.html" %}

{% block page_title %}外伝クエスト{% endblock %}

{% block content %}

<!-- 外典クエストタスクカードの設置-->
{% for gaiden in gaidens %}
{% with forloop.counter as outer_counter %}
<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ gaiden.title }}</h5>

        <!-- 外典クエスト達成率カードの設置-->
        {% for achievement_rate in achievement_rates %}
        {% with forloop.counter as inner_counter %}
        {% if outer_counter == inner_counter %}
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">あなたの{{ gaiden.title }}の達成率は</h5>
                <div class="progress">
                    <div id="story-achieve-rate-bar-{{ gaiden.task_seq }}" class="progress-bar progress-bar-striped progress-bar-animated" 
                    role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width:{{ achievement_rate }}%;text-align:center;"></div>
                </div>
                <div class="progress-values" style="text-align:center;">
                    <h3 id="story-achieve-rate-{{ gaiden.task_seq }}">{{ achievement_rate }}%です</h3>
                </div>
            </div>
        </div>
        {% endif %}
        {% endwith %}
        {% endfor %}

<div style="height:2vh;"></div>

        {% load sort_tasks %}

        <!-- 新規タスクのみの一覧を出す -->
        <div class="new-tasks">
            {% for task in gaiden.subtask_set.all|sort_task:'task_seq' %}
            {% if task.condition == 1 %}
            <div data-num="{{ task.task_seq }}">
                <div class="card task-contents" style="padding:0.3rem;">
                    <div class="row">
                        <div class="col-md-1" style="padding:0 0 0 30px;">
                            <div class="success_btn" data-taskid="{{ task.id }}" data-condition="{{ task.condition }}" data-reqtype="gaiden" data-mainseq="{{ gaiden.task_seq }}"></div>
                        </div>
                        <div class="col-md-11">
                            <p>{{ task.title }}</p>
                        </div>
                    </div>
                </div>
                <div class="card-space" style="height:0.3vh;"></div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        
        <div style="text-align:right;">
            <a class="fintask-btn" style="cursor:pointer;">完了済タスクを見る</a>
        </div>

        <!-- 完了タスクのみを出す(最初はここ非表示の予定) -->
        <div class="fin-tasks">
            {% for task in gaiden.subtask_set.all|sort_task:'task_seq' %}
            {% if task.condition == 3 %}
            <div data-num="{{ task.task_seq }}">
                <div class="card task-contents" style="padding:0.3rem;">
                    <div class="row">
                        <div class="col-md-1" style="padding:0 0 0 30px;">
                            <div class="success_btn clicked" data-taskid="{{ task.id }}" data-condition="{{ task.condition }}" data-reqtype="gaiden" data-mainseq="{{ gaiden.task_seq }}"></div>
                        </div>
                        <div class="col-md-11">
                            <p>{{ task.title }}</p>
                        </div>
                    </div>
                </div>
                <div class="card-space" style="height:0.3vh;"></div>
            </div>
            {% endif %}
            {% endfor %}
        </div>


    </div>
</div>
<div style="height:1.5vh;"></div>
{% endwith %}
{% endfor %}

{% endblock %}

templates/base (2020:12:03 0:57).html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
        <!-- CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        {% block extra_css %}{% endblock %}

        <title>{% block page_title %}{% endblock %}</title>

        <script>
            // ドキュメントがリロードされた後に読み込む設定
            document.addEventListener('DOMContentLoaded',function(){
                // 初期表示の設定
                $('.menu-content').toggle();
                $('.click-menu').toggle();
                $('.fin-tasks').toggle();
                //$('.main-contents').toggleClass('click-menu-open');

                // カード一覧をカスタムデータnumを使ってidの降順に並び替える
                function sortCard(cards){
                    var sortedCards = cards.sort(function(a,b){
                        // console.log($(a).data('num'));
                        // a,bのカスタムデータを取得
                        var aNum = $(a).data('num');
                        var bNum = $(b).data('num');

                        // 昇順ソート(不等号を逆にすれば降順にもできる)
                        if(Number(aNum) > Number(bNum)){
                            return 1;
                        }else if(Number(aNum) < Number(bNum)){
                            return -1;
                        }
                        return 0;
                    });
                    // console.log(sortedCard);
                    return sortedCards;
                }
                
                // メニューボタンのクリックイベント
                $('.menu-btn').click(function(){
                    $('.menu-content').stop(true).toggle('fast');
                    $('.click-menu').stop(true).animate({'width':'toggle'});
                    $('.main-contents').stop(true).toggleClass('click-menu-open');
                });

                // 完了済タスクを見るボタンのクリックイベント
                $('.fintask-btn').click(function(){
                    var $this = $(this);
                    var pare = $this.parent();
                    pare.siblings('.fin-tasks').slideToggle();
                });


                
                // $('.success_btn').click(function(){
                //     console.log("success-btnがクリックされました");
                //     var $this = $(this);
                //     var taskId = $this.data('taskid');
                //     var condition = $this.data('condition');
                //     var card = $this.parents('.card.task-contents');
                //     var finTasks = card.parents('.card-body').children('.fin-tasks');
                //     var newTasks = card.parents('.card-body').children('.new-tasks');
                //     $.ajax({
                //         type:"get",
                //         url:"{% url 'app:condition_change' %}",
                //         dataType:"json",
                //         data:{
                //             "task_id":taskId,
                //             "condition":condition
                //         }
                //     })
                //     .done(function(data){
                //         console.log('Ajax Success'); //[DEBUG]
                //         $this.stop(true).toggleClass('clicked');
                //         if(condition == "1"){
                //             $this.data('condition',"3");
                //             card.parent().appendTo(finTasks);
                //             // card.siblings('.card-space').appendTo(finTasks);
                //             // 移動したタスクの並び替え
                //             // console.log(finTasks.children());//[DEBUG]
                //             var sortedFinTasks = sortCard(finTasks.children());
                //             console.log(sortedFinTasks);
                //             // console.log(finTasks.children()); //[DEBUG]
                //             finTasks.empty();
                //             sortedFinTasks.each(function(){
                //                 finTasks.append($(this));
                //             });
                //         }else if(condition == "3"){
                //             $this.data('condition',"1");
                //             card.parent().appendTo(newTasks);
                //             // card.siblings('.card-space').appendTo(newTasks);
                //             // 移動したタスクの並び替え
                //             // console.log(newTasks.children()); //[DEBUG]
                //             var sortedNewTasks = sortCard(newTasks.children());
                //             console.log(sortedNewTasks); //[DEBUG]
                //             newTasks.empty();
                //             sortedNewTasks.each(function(){
                //                 newTasks.append($(this));
                //             });
                //         }
                //         // card.slideToggle('fast');
                //     }).fail(function(msg){
                //         console.log('Ajax Error');
                //         // console.log(taskId);
                //         // console.log(condition);
                //     });
                // });

                // $('.test-btn').click(function(){
                //     var $this = $(this);
                //     var place = $this.data('place');
                //     console.log($this);
                //     console.log(place);
                //     if(place == "a"){
                //         console.log("aん飛んでます");
                //         $this.data('place',"b")
                //         $this.appendTo($('.bbb'));
                //     }else if(place == "b"){
                //         console.log("bに飛んでます");
                //         $this.data('place',"a");
                //         $this.appendTo($('.a'));
                //     }
                // });
            });

            $(document).on('click','.success_btn',function(){
                var $this = $(this);
                console.log($this[0]);
                // var taskId = $this.data('taskid');
                var condition = $this.data('condition');
                var card = $this.parents('.card.task-contents');

                // 完了ボタンのクラスの切り替え(見た目の変化)
                $this.stop(true).toggleClass('clicked');

                if(condition == "1"){
                    var finTasks = card.parents('.card-body').children('.fin-tasks');
                    // 状態変化+完了タスクリストに入れる
                    $this[0].dataset.condition = "3";
                    card.parent().appendTo(finTasks);

                    // 並び替え
                    var sortedFinTasks = sortCard(finTasks.children());
                    finTasks.empty();
                    sortedFinTasks.each(function(){
                        finTasks.append($(this));
                    });
                    console.log("完了");
                }else if(condition == "3"){
                    var newTasks = card.parents('.card-body').children('.new-tasks');
                    // 状態変化+新規タスクリストに入れる
                    $this[0].dataset.condition = "1";
                    card.parent().appendTo(newTasks);

                    // 並び替え
                    var sortedNewTasks = sortCard(newTasks.children());
                    newTasks.empty();
                    sortedNewTasks.each(function(){
                        newTasks.append($(this));
                    });
                    console.log("完了");
                }
            });
            
        </script>
      </head>

      <body>
        <header style="background-image:url({% static 'images/anaden_header.JPG' %});">
            <div class="logo" style="float:left;">
                <a href="/">
                    <div style="width:200px;height:60px;background-color:skyblue;opacity:0.5;">anaden-tool</div>
                </a>
            </div>
            <div class="menu-btn" style="float:right;">
                <a id="menu">
                    <div style="width:50px;height:60px;background-color:#eee;opacity:0.5;"></div>
                </a>
                
            </div>
            <div style="clear:both;"></div>
        </header>

        <!-- <div class="test">
            <div class="a">
                <a class="test-btn" data-place="a">osutoidou</a>
            </div>
            <div class="bbb">
    
            </div>
        </div> -->

        <div id="wrap" style="position:relative;">
            <div class="contents">
                <div class="click-menu">
                    <div class="menu-content-box pr-5"></div>
                    <div class="menu-content pr-5 pt-3">
                        <a href="#story" class="menu-link">ストーリー</a>
                    </div>
                    <div class="menu-content pr-5 pt-3">
                        <a href="#other_story" class="menu-link">外伝</a>
                    </div>
                    <div class="menu-content pr-5 pt-3">
                        <a href="#other" class="menu-link">その他</a>
                    </div>
                    <div class="menu-content pr-5 pt-3">
                        <a href="#task_management" class="menu-link">やること管理</a>
                    </div>
                    <div class="menu-content pr-5 pt-3">
                        <a href="#fishing" class="menu-link">釣り管理</a>
                    </div>
                    <div class="menu-content pr-5 pt-3">
                        <a href="#mypage" class="menu-link">マイページ</a>
                    </div>
                </div>
                <div class="main-contents">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
        <footer></footer>

    
        <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
        <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" 
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
        <script src="https://code.jquery.com/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
        {% block extra_js %}{% endblock %}
      </body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
        <!-- CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        {% block extra_css %}{% endblock %}

        <title>{% block page_title %}{% endblock %}</title>

      </head>

      <body>
        <header style="background-image:url({% static 'images/anaden_header.JPG' %});">
            <!-- タイトル(トップへ戻る) -->
            <div class="logo" style="float:left;">
                <a href="/">
                    <div style="width:200px;height:60px;background-color:skyblue;opacity:0.5;">anaden-tool</div>
                </a>
            </div>
            <!-- サイドバーメニュー開閉ボタン -->
            <div class="menu-btn" style="float:right;">
                <a id="menu">
                    <div style="width:50px;height:60px;background-color:#eee;opacity:0.5;"></div>
                </a>
                
            </div>
            <div style="clear:both;"></div>
        </header>

        <div id="wrap" style="position:relative;">
            <div class="contents">
                <!-- メニューサイドバー -->
                <div class="click-menu">
                    <div class="menu-content-box pr-5"></div>
                    <div class="menu-content pr-5 pt-3">
                        <a href="{% url 'app:storys' %}" class="menu-link">ストーリー</a>
                    </div>
                    <div class="menu-content pr-5 pt-3">
                        <a href="{% url 'app:gaitens' %}" class="menu-link">外典</a>
                    </div>
                    <div class="menu-content pr-5 pt-3">
                        <a href="{% url 'app:gaidens' %}" class="menu-link">外伝</a>
                    </div>
                    <div class="menu-content pr-5 pt-3">
                        <a href="{% url 'app:kaikous' %}" class="menu-link">邂逅</a>
                    </div>
                    <div class="menu-content pr-5 pt-3">
                        <a href="{% url 'app:dansyos' %}" class="menu-link">断章</a>
                    </div>
                    <div class="menu-content pr-5 pt-3">
                        <a href="{% url 'app:kyosous' %}" class="menu-link">協奏</a>
                    </div>
                    <div class="menu-content pr-5 pt-3">
                        <a href="#mypage" class="menu-link">マイページ</a>
                    </div>
                </div>
                <div class="main-contents">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
        <footer></footer>

    
        <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
        <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" 
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
        <script src="https://code.jquery.com/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
        {% block extra_js %}{% endblock %}
      </body>
</html>